---@class ballerina.LspConfig
---@field enabled boolean Start the Ballerina language server for .bal buffers.
---@field root_markers string[] Files/directories that mark the workspace root.
---@field file_watch boolean Let the client watch the workspace for external
---file changes (:h lsp-file-watch) and notify the server. On by default, so
---the server picks up files it did not get through Neovim itself: git
---checkouts/pulls, and `.bal` source generated by `bal openapi`/`bal
---graphql`/`bal grpc`/`bal persist generate` run outside Neovim. Watching is
---scoped to Ballerina's own package structure (ballerina.lsp_watch) rather
---than a single recursive watch over the whole workspace, so a build cache
---such as `target/` or `.gradle/` is never watched even if it contains a
---pathologically long or invalid path (the crash this used to cause on
---macOS -- see README Troubleshooting). Turn off only if you hit a case the
---scoping doesn't cover; edits made through Neovim itself always reach the
---server regardless of this setting.
---@field config table? Extra fields merged into the LSP client config, e.g.
---`capabilities`, `settings`, `init_options` (see :h vim.lsp.Config).

---@class ballerina.DapConfig
---@field enabled boolean Register the nvim-dap adapter/configurations when
---nvim-dap is installed.

---@class ballerina.Config
---@field bal_cmd string? Path to the `bal` binary. nil = auto-detect (PATH,
---then $BALLERINA_HOME, then the known install locations of the official
---distributions).
---@field bal_home string? Path to a Ballerina distribution root (the
---BALLERINA_HOME layout, with bin/bal inside); the `bal` launcher is resolved
---from it. Useful for language developers pointing the plugin at a locally
---built distribution. Ignored when bal_cmd is set. nil = auto-detect.
---@field format_on_save boolean Run `bal format` after saving a .bal file.
---@field indent boolean Use the bundled brace/paren-aware indentexpr.
---@field lsp ballerina.LspConfig
---@field dap ballerina.DapConfig

local M = {}

---@type ballerina.Config
M.defaults = {
  bal_cmd = nil,
  bal_home = nil,
  format_on_save = true,
  indent = true,
  lsp = {
    enabled = true,
    root_markers = { "Ballerina.toml" },
    file_watch = true,
    config = nil,
  },
  dap = {
    enabled = true,
  },
}

M.options = vim.deepcopy(M.defaults)

---@param opts ballerina.Config|table|nil
M.setup = function(opts)
  opts = opts or {}
  vim.validate("bal_cmd", opts.bal_cmd, "string", true)
  vim.validate("bal_home", opts.bal_home, "string", true)
  vim.validate("format_on_save", opts.format_on_save, "boolean", true)
  vim.validate("indent", opts.indent, "boolean", true)
  vim.validate("lsp", opts.lsp, "table", true)
  vim.validate("dap", opts.dap, "table", true)

  M.options = vim.tbl_deep_extend("force", vim.deepcopy(M.defaults), opts)
end

return M
